remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-remote-theme

title: Swapnil Lahu Lonkar
description: B.Tech Electronics & Telecommunication Engineering Student | MIT Academy of Engineering
